### ISSUE TITLE
Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by docmagic** [wardforthmann/gobble#3]
Directory traversal also known as path traversal vulnerability has been detected in the code. Using this an attacker can traverse the server directory and go to places where he do not have the access for. This vulnerability can result in information disclosure of the sensitive files as well.

**Payload used/Steps to reproduce:**
We have developed a curl command to show the resulting behavior that has been published in our internal JIRA ticket IN-401

**Output:**
You will see the output of the passwd file (user list) which can be used for further attacks like brute forcing passwords.

**Helpful link to mitigate:**
https://www.owasp.org/index.php/File_System#Path_traversal

**Comment by wardforthmann** [comment]
This has been resolved as of tag v1.4
